[project]
name = "Customer Order Pattern Analysis"
description = "Analyze Blinkit-like customer behavior using the Instacart Market Basket Analysis dataset"

[data]
source_url = "https://www.kaggle.com/datasets/instacart/market-basket-analysis"

[theme]
base="light"
primaryColor="#00A36C"
font="sans serif"
